privatekey = ""
coralogix_region = ""
application_name = "test-tf-integration"
subsystemName = "test-tf-integration"
firehose_stream = "fh-stream"
log_group_name = "can-delete"
log_group = "fh-stream-lg"